name:                wreq-attempt
version:             1.0.0.0
author:              Author name here
maintainer:          example@example.com
copyright:           "MIT"

dependencies:
  - base
  - wreq
  - aeson
  - lens


library:
  source-dirs: app
